testrpc:
    build: ./dockerfiles/testrpc
    ports:
        - "8545:8545"

truffle:
    image: acdcjunior/truffle:3.4.5
    links:
        - testrpc
    volumes:
        - "./catalogo-project:/catalogo"
    working_dir: /catalogo
    stdin_open: true
    tty: true
    command: truffle console --network unbtest
